moveit/moveit_task_constructor

- core/demo/CMakeLists.txt
- core/demo/plan_pick_pa10.cpp
- core/demo/plan_pick_ur5.cpp
- core/include/moveit/task_constructor/properties.h
- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/stages/cartesian_position_motion.h
- core/include/moveit/task_constructor/stages/generate_grasp_pose.h
- core/include/moveit/task_constructor/stages/gripper.h
- core/include/moveit/task_constructor/stages/move.h
- core/include/moveit/task_constructor/storage.h
- core/include/moveit/task_constructor/task.h
- core/src/CMakeLists.txt
- core/src/container.cpp
- core/src/introspection.cpp
- core/src/properties.cpp
- core/src/stage.cpp
- core/src/stages/cartesian_position_motion.cpp
- core/src/stages/generate_grasp_pose.cpp
- core/src/stages/gripper.cpp
- core/src/stages/move.cpp
- core/src/storage.cpp
- core/src/task.cpp
- core/test/CMakeLists.txt
- core/test/test_plan_generate_grasp_pose.cpp
- core/test/test_properties.cpp
- msgs/CMakeLists.txt
- msgs/msg/Property.msg
- msgs/msg/StageDescription.msg
Replacement for #9, implementing the `PropertyMap` we discussed a while ago.
Using this `PropertyMap` I also generalized the grasp frame specification for `GenerateGraspPose` - getting rid of hard-coded YPR angles. This allows for our PA10 example to be included easily.
I merged already with master to fix conflicts due to reordering of source files in cmake.
> PropertyMap implementation

- visualization/motion_planning_tasks/src/task_display.cpp
- visualization/motion_planning_tasks/src/task_display.h
- visualization/visualization_tools/include/moveit/visualization_tools/marker_visualization.h
- visualization/visualization_tools/include/moveit/visualization_tools/task_solution_visualization.h
- visualization/visualization_tools/src/marker_visualization.cpp
- visualization/visualization_tools/src/task_solution_visualization.cpp
So far markers had to be specified w.r.t. the planning frame. In 936681f4c3a69079a35345caa8680d95654e6f53 this was relaxed to allow for arbitrary reference frames. However, the marker pose was only evaluated once, i.e. markers attached to a link did not move during trajectory display. This PR now allows full flexibility.
> online update of relative markers

- core/src/stages/move_relative.cpp
Warnings were named after a different class. This can be a bit confusing while debugging.
> MoveRelative: renamed prints to fit class name

- core/src/properties.cpp
PropertyMap::exposeTo is given the parameter other_name which should be the new name of the exposed property, but the old name was used instead.
> PropertyMap::exposeTo fix: use other_name as new name for property

- core/include/moveit/task_constructor/solvers/cartesian_path.h
It would be nice to have some automated way to add them via C++1x magic,
but I'm not aware of something like that at the moment.
> expose typed setters in Cartesian solver

- core/include/moveit/task_constructor/storage.h
- core/src/storage.cpp
- core/test/CMakeLists.txt
- core/test/test_interface_state.cpp
This PR was originally proposed by @v4hn. 
Also update sorted interface when state becomes inf or get's new cost.
> inf cost states always go last

- .rosinstall
- .travis.yml
- README.md
- core/CMakeLists.txt
- core/include/moveit/task_constructor/stage.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/task.cpp
Addresses #67 by augmenting the error message with the corresponding flow symbol used in rviz.
In order to fix the broken Travis, I had to add some more commits meanwhile. Please fast-forward for merging.
> improve error msg for mismatching container/child interfaces

- core/include/moveit/task_constructor/properties.h
- core/src/introspection.cpp
- core/src/properties.cpp
- core/src/stages/move_relative.cpp
- core/src/stages/move_to.cpp
- core/test/test_properties.cpp
- msgs/msg/Property.msg
- visualization/motion_planning_tasks/properties/CMakeLists.txt
- visualization/motion_planning_tasks/properties/property_factory.cpp
- visualization/motion_planning_tasks/properties/property_factory.h
- visualization/motion_planning_tasks/properties/property_from_yaml.cpp
- visualization/motion_planning_tasks/src/factory_model.h
- visualization/motion_planning_tasks/src/local_task_model.cpp
- visualization/motion_planning_tasks/src/local_task_model.h
- visualization/motion_planning_tasks/src/pluginlib_factory.h
- visualization/motion_planning_tasks/src/remote_task_model.cpp
- visualization/motion_planning_tasks/src/remote_task_model.h
- visualization/motion_planning_tasks/src/task_display.cpp
- visualization/motion_planning_tasks/src/task_list_model.cpp
- visualization/motion_planning_tasks/src/task_list_model.h
- visualization/motion_planning_tasks/src/task_panel.cpp
- visualization/motion_planning_tasks/test/test_task_model.cpp
First attempt to display mtc properties in rviz. For each stage, a separate `rviz::PropertyTreeModel` is maintained. It's possible to register custom `rviz::Property` factory functions with the `PropertyFactory`.
These custom properties might allow nice editing, e.g. using interactive markers to configure a `StampedPose`.
A generic creator function, creates an rviz::Property tree from serialized YAML. Streaming a ROS type, generates YAML-like text. Unfortunately it's not perfect YAML (in contract to Python). For example, sequences as in [`moveit_msgs/Constraints`](http://docs.ros.org/melodic/api/moveit_msgs/html/msg/Constraints.html) are not correctly handled.
An alternative implementation would have used [ros-type-introspection](http://wiki.ros.org/ros_type_introspection). However, …
> rviz: property visualization

- core/include/moveit/task_constructor/properties.h
- core/src/properties.cpp
- core/src/stages/compute_ik.cpp
- core/src/stages/move_relative.cpp
- core/src/stages/move_to.cpp
Addresses #79.
Also reduces default timeout for `MoveTo` / `MoveRelative` stages from 10s to 1s.
**This PR branch is included in #81. Please, fast-forward to #81 for merging.**
> ComputeIK: set default timeout from JMG

- .rosinstall
To run the demo of the moveit-master branch, an open gripper pose is missing, 
``` [ERROR] [1574258838.504600244]: Initialization failed: Error initializing stage:
generate grasp pose: unknown end effector pose: open
```
solution is to use the latest melodic-devel branch of panda_moveit_config
a PR for the doc that is related to this will be also provided.
> external source needed in moveit-master branch

- demo/launch/demo.launch
With demo.launch it was not possible to execute found solutions because the required capability was not loaded.
This commit fixes this issue by adding the capability's name to move_group's _capabilities_ parameter.
> Load ExecuteTaskSolutionCapability in demo.launch

- core/include/moveit/task_constructor/task.h
- core/include/moveit/task_constructor/task_p.h
- core/src/task.cpp
This adds a convenient callback for getting the newest solution of the current task planning instance. Using the TaskCallback would require keeping track of all solutions and compare which is the newest one as `solutions()` returns all solutions ordered by cost.
> Add public SolutionCallback interface to Task

- demo/src/pick_place_task.cpp
Previous code was generating the error on changing object_name in config/panda_config.yaml file because of this bug as here we are overwriting the object_name as "object" which brought the inconsistency in code.
> Generalised code for object_name

- demo/src/moveit_task_constructor_demo.cpp
Previous code will print/log "Execution complete" even if the execution was disabled.
> Printing success log only if execution completes

- capabilities/CMakeLists.txt
- core/CMakeLists.txt
This is required if you are compiling MTC against moveit/master in xenial (gcc-5.5 does not compile with C++11 by default)
> Added C++11 flags for MOVEIT_MASTER check

- core/CMakeLists.txt
- core/include/moveit/task_constructor/container.h
- core/src/container.cpp
- visualization/motion_planning_tasks/src/local_task_model.cpp
- visualization/motion_planning_tasks/src/local_task_model.h
As a follow-up to #119, this PR replaces all uses of private API in the `visualization` package, making the code slightly harder to read in my opinion. @v4hn if you approve, I suggest fast-forwarding.
> Avoid private API

- visualization/package.xml
Because rviz does not `export_build_depend` qtbase5-dev, a system without it will not compile properly. (tested on dockerized CI with ubuntu:bionic as base image and rosdep as dependency solving utility).
```
CMake Error at CMakeLists.txt:24 (find_package): 
By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Qt5", but
CMake did not find one.
Could not find a package configuration file provided by "Qt5" (requested
version 5.9.5) with any of the following names:
Qt5Config.cmake
qt5-config.cmake
Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
to a directory containing one of the above files.  If "Qt5" provides a
separate development package or SDK, be sure it has been installed.
```
> Added qtbase5-dev as build_depend

- visualization/CMakeLists.txt
- visualization/icons/classes/Motion Planning Tasks.svg
Obviously not the most pressing issue, but nice to have.
I quite like the idea of multiple MoveIt logos resembling a conveyor belt.
The original SVG was taken from MoveIt's press kit.
@davetcoleman I hope it is ok for us to use this as a logo?
> add an icon for the RViz interface

- core/test/CMakeLists.txt
- visualization/motion_planning_tasks/test/CMakeLists.txt
Otherwise these suddenly started to fail for me on Lunar Linux
because gmock headers were no longer included.
> build tests using gmock via catkin_add_gmock

- core/CMakeLists.txt
This makes sure that code using `pimpl()` will not compile out of the box unless the `*_p.h` header is included.
Personally, I'm not sure we actually need it, but then again, why should the libraries contain copies of inline functions anyway?
Compatible with Clang and GCC
> do not export inline functions

- .travis.yml
- visualization/visualization_tools/include/moveit/visualization_tools/display_solution.h
- visualization/visualization_tools/src/display_solution.cpp
Store the set of joints involved in received solution trajectories and
use this set to constrain serialization of solutions for execution to those joints only.
If this is not done, all joints of the RobotModel are considered for the trajectory,
but we might not have controllers defined for all joints, so execution will fail.
Maybe, a better approach might be to just ask the MTC planner to execute a specific solution id.
However, this requires that the planner node is still available.
This relies on https://github.com/ros-planning/moveit/pull/1927, which is merged into master + melodic, but not yet released.
> fix rviz solution execution

- core/include/moveit/task_constructor/solvers/pipeline_planner.h
- core/src/solvers/pipeline_planner.cpp
This adds the ability to construct PipelinePlanner from PlanningPipelinePtr, the current implementation always construct  `planner_`  by using `Task::createPlanner` [see](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/solvers/pipeline_planner.cpp#L71) but this expect the parameters to be loaded under `move_group` namespace [see](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/include/moveit/task_constructor/task.h#L78) which isn't always the case (for example when using moveit_cpp) -- another solution would be adding a new property `p.declare<std::string>("planner_ns", "move_group", "desc");` and using it in the `PipelinePlanner::init` function but doing so is resulting into a segfault with the following backtrace (it find the …
> Allow constructing PipelinePlanner from PlanningPipelinePtr

- core/include/moveit/task_constructor/stage.h
I couldn't find a specific bug for gcc5 for this error, but there are plenty of bugs in constexpr evaluation reported in bugzilla so I am not surprized this one exist.
Changing the syntax to the following compiles without problems.
Tested on 16.04 with ROS Kinetic and master branch of moveit.
> Fix for GCC5 (Ubuntu 16.04 / Kinetic) call to non-constexpr function

- codecov.yaml
With some recent changes in the ros-planning organization
it looks like Codecov got enabled for this project too.
https://github.com/ros-planning/moveit_task_constructor/pull/167#issuecomment-642476913
It's good to have the check around, but -0.03% is not supposed to fail.
> use MoveIt's codecov configuration

- core/src/introspection.cpp
- core/src/task.cpp
So far, the `start_scene` field of a `SolutionMsg` was only filled by `Introspection::fillSolution()`,
but not yet by `Task::execute()`. This PR fixes #171.
I also considered filling `start_scene` in `SolutionBase::fillMessage()`. However, for sequences, this field would have been filled multiple times then, which is not an option.
> SolutionMsg: always fill start_scene

- README.md
- visualization/CMakeLists.txt
Avoid error about moc_xxx files not found.
Without this, compiler only search in local directory instead of catkin build directory where the moc_xxx files are generated. @henningkayser repository had this correction in his CMakelists.
> Updated CMakeLists

- visualization/motion_planning_tasks/src/local_task_model.cpp
- visualization/motion_planning_tasks/src/remote_task_model.cpp
- visualization/motion_planning_tasks/src/remote_task_model.h
- visualization/motion_planning_tasks/src/task_list_model.cpp
- visualization/motion_planning_tasks/src/task_list_model.h
- visualization/motion_planning_tasks/src/task_panel.cpp
- visualization/motion_planning_tasks/src/task_panel.h
- visualization/motion_planning_tasks/src/task_panel.ui
- visualization/motion_planning_tasks/src/task_view.ui
There's no need for individually resizable columns, but all numeric content should autoresize and be visible all the time.
We might want to add an option to hide the new time column in the future.
Remove intermediate AutoAdjustingTreeView layer to simplify code.
Resizing the columns did not work perfectly well before and the auto_hide_cols_ feature was not really used.
Lastly, the solution view is conceptually no tree view, so rework it to a table view.
This was a view of the old panel, without a lot of manual layout changes, illustrating issues:
Here is a similar view with the modifications:
> rework RViz panel

- core/package.xml
- core/test/test_stage.launch
- visualization/motion_planning_tasks/test/test_task_model.launch
- visualization/package.xml
CI fails after the recent moveit_resources split:
https://travis-ci.com/github/ros-planning/moveit_task_constructor/jobs/375505517#L931
> adapt tests to new moveit_resources layout

- demo/src/pick_place_task.cpp
In the panda example, the `hand` group was "hand" as well, so it didn't make a difference... However, if the group has a different name, it's important to either inherent from the correct parent property (`hand`) or to directly set the correct name.
Fixes #204.
> Fix pick-place-demo: Correctly set hand group

- visualization/visualization_tools/CMakeLists.txt
- visualization/visualization_tools/src/marker_visualization.cpp
Just a simple compile-time switch to handle removed rviz' `getTFClient()` in Noetic.
> tf2 compatibility for Noetic

- core/include/moveit/task_constructor/task.h
- core/src/task.cpp
I have found that when one of the stages is struggling to find a solution the task can get stuck planning forever, so in this PR I exposed the setTimeout function and made the task fail if it exceeded the time
> Task: Add ability to set timeout

- core/include/moveit/task_constructor/task.h
- core/include/moveit/task_constructor/task_p.h
- core/src/introspection.cpp
- core/src/task.cpp
- msgs/msg/Solution.msg
- msgs/msg/TaskDescription.msg
- msgs/msg/TaskStatistics.msg
- visualization/motion_planning_tasks/src/remote_task_model.cpp
- visualization/motion_planning_tasks/src/remote_task_model.h
- visualization/motion_planning_tasks/src/task_display.cpp
- visualization/motion_planning_tasks/src/task_display.h
- visualization/motion_planning_tasks/src/task_list_model.cpp
- visualization/motion_planning_tasks/src/task_list_model.h
- visualization/motion_planning_tasks/test/CMakeLists.txt
- visualization/motion_planning_tasks/test/test_task_model.cpp
- visualization/motion_planning_tasks/test/test_task_model.launch
The original design of the ROS API for introspection had several issues causing segfaults on both sides:
* While it was perfectly possible to create multiple tasks publishing on the same topic, the rviz side wasn't able to handle this.
* Additionally, multiple tasks publishing on the same topic caused conflicts when attempting to create multiple get-solution-services.
This PR:
* Adapts messages to encode a unique `task_id`, replacing previous `process_id` + `id`
* The role of `Task::id` was actually a namespace, so its named `ns` now.
* Creates a get-solution-service for each task using its unique `task_id` as service name. 
As this service should be only used for communication between rviz and the task-creating process, that should be fine. 
If needed, the `task_id` can be read from …
> Rework rviz introspection

- core/include/moveit/task_constructor/task.h
- core/include/moveit/task_constructor/task_p.h
- core/src/introspection.cpp
- core/src/stages/connect.cpp
- core/src/stages/move_to.cpp
- core/src/task.cpp
- core/test/test_container.cpp
- msgs/msg/Solution.msg
- msgs/msg/TaskDescription.msg
- msgs/msg/TaskStatistics.msg
- visualization/motion_planning_tasks/properties/property_from_yaml.cpp
- visualization/motion_planning_tasks/src/remote_task_model.cpp
- visualization/motion_planning_tasks/src/remote_task_model.h
- visualization/motion_planning_tasks/src/task_display.cpp
- visualization/motion_planning_tasks/src/task_display.h
- visualization/motion_planning_tasks/src/task_list_model.cpp
- visualization/motion_planning_tasks/src/task_list_model.h
- visualization/motion_planning_tasks/src/task_panel.cpp
- visualization/motion_planning_tasks/src/task_panel.h
- visualization/motion_planning_tasks/src/task_panel_p.h
- visualization/motion_planning_tasks/test/CMakeLists.txt
- visualization/motion_planning_tasks/test/test_task_model.cpp
- visualization/motion_planning_tasks/test/test_task_model.launch
- visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp
- visualization/motion_planning_tasks/utils/tree_merge_proxy_model.cpp
Combining PRs #214 + #215 and resolving their conflicts. **Merge from cmdline via fast-forwarding.**
Additionally, this PR adds configurable handling of destroyed remote tasks. They can be:
- always kept (marked red). Of course, one still cannot fetch new solutions in this state.
- replaced with next task (with same `task_id`)
- immediately removed from list
> fast-forward master

- capabilities/CMakeLists.txt
- core/CMakeLists.txt
- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/cost_terms.h
- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/storage.h
- core/src/container.cpp
- core/src/cost_terms.cpp
- core/src/stage.cpp
- core/src/stages/connect.cpp
- core/src/storage.cpp
- core/test/CMakeLists.txt
- core/test/test_container.cpp
- core/test/test_interface_state.cpp
- core/test/test_serial.cpp
- demo/CMakeLists.txt
- msgs/CMakeLists.txt
- rviz_marker_tools/CMakeLists.txt
- visualization/CMakeLists.txt
Fixes #218. Fixes #182.
The `SerialContainer` was accepting solution sequences comprising a failure-only `Connect` stage, because the `Connect` stage didn't correctly mark its sequentialized subsolutions as a failure (but only the overall sequence). @JafarAbdi, please validate that this solves your issue.
> Fix SerialContainer

- demo/launch/demo.launch
- demo/package.xml
In Noetic, the tutorial demos don't work anymore, because Franka has changed the collision model of the robot.
As a quick hack for this, this PR switches to the old Panda config, available in `moveit_resources`.
> demo: switch to moveit_resources_panda_moveit_config

- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/task.h
- core/package.xml
- core/src/container.cpp
- core/src/task.cpp
- core/test/test_container.cpp
We do use ROS in the background. But there is no need for a public export dependency on it.
This patch also resolves the following catkin_lint issue:
moveit_task_constructor_core: CMakeLists.txt(17): error: package 'roscpp' must be in CATKIN_DEPENDS in catkin_package()
I also see this other warning which we might want to address, but I'm not convinced it's worth the additional include directives in dependent targets.
moveit_task_constructor_core: src/CMakeLists.txt(37): warning: target_include_directories() exports external PUBLIC path '${catkin_INCLUDE_DIRS}'
> remove roscpp as an export dependency for the core package

- core/src/stage.cpp
Fixup for 10f6b7a58ed6063771eb7b9cbe9931fc71497ca8 .
On my release workspace I see
/usr/bin/ld: libmoveit_task_constructor_core_stages.so: undefined reference to `
void moveit::task_constructor::PropagatingEitherWay::send<(moveit::task_constructor::Interface::Direction)0>(moveit::task_constructor::InterfaceState const&, moveit::task_constructor::InterfaceState&&, moveit::task_constructor::SubTrajectory&&)'
/usr/bin/ld: libmoveit_task_constructor_core_stages.so: undefined reference to `
void moveit::task_constructor::PropagatingEitherWay::send<(moveit::task_constructor::Interface::Direction)1>(moveit::task_constructor::InterfaceState const&, moveit::task_constructor::InterfaceState&&, moveit::task_constructor::SubTrajectory&&)'
and indeed the methods are not explicitly instantiated and not …
> explicitly instantiate template for required values

- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/storage.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/storage.cpp
- core/test/test_interface_state.cpp
- core/test/test_serial.cpp
With #220 I essentially disabled pruning to fix some urgent issues. It turned out that this feature wasn't fully thought about and it was broken literally everywhere. This is my work-in-progress to re-enable that important feature (or make it work in the first place).
I noticed several things:
- The action to be taken for pruning is highly dependent based on the stage that triggers it. 
- Generator-like stages shouldn't trigger pruning at all: They just don't push new states to their push interfaces.
- Propagator stages can _remove_ all interface states that are incoming to the failed source state.
However, this rule only applies to the default propagators MoveTo and MoveRelative that forward states in a 1:1 fashion.
If the propagator generates multiple output states for each input state, …
> Rework Pruning

- core/include/moveit/task_constructor/solvers/pipeline_planner.h
- core/include/moveit/task_constructor/task.h
- core/src/solvers/pipeline_planner.cpp
- core/src/task.cpp
https://github.com/ros-planning/moveit/pull/2127 merged support
for multiple planner plugins. As a result, the planner specification
should include a pipeline name from now on.
Support the new schema and provide a fallback for older configurations.
While doing so, I moved the create methods to the class they actually belong to
and introduced a clean options parameter
This change is somewhat urgent because the pickplace demo is broken since moveit/2127 was merged.
> rework PipelinePlanner creation

- core/src/stages/move_relative.cpp
- rviz_marker_tools/include/rviz_marker_tools/marker_creation.h
- rviz_marker_tools/src/marker_creation.cpp
Implementation for this [TODO](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stages/move_relative.cpp#L273)
The `MoveRelative` stage can now be visualized as a red-green arrow, where the red part shows the invalid part and the green part shows the valid part of the plan. The construction of the arrow is different for forward and backward propagators.
For forward propagators, it looks like this:
https://user-images.githubusercontent.com/57101356/114857654-cfd8d680-9de8-11eb-8a97-ac9b20e298d0.mp4
and for backward propagators like this:
https://user-images.githubusercontent.com/57101356/114857852-0d3d6400-9de9-11eb-9021-32ebb64ec019.mp4
Unfortunately, for forward propagators with only short invalid parts, the arrow tip looks weird: …
> improve visualization for MoveRelative stage

- core/include/moveit/task_constructor/stages/move_to.h
- core/src/stages/move_to.cpp
Implementation for this [TODO](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stages/move_to.cpp#L182).
The `MoveTo` stage can now visualize both Point and Pose goals. The frame for the target is now derived from `target_eigen` instead of the target message itself, because `target_eigen` is computed in both `getPoseGoal` and `getPointGoal`.
> Add visualization for Point goals

- core/include/moveit/task_constructor/cost_terms.h
- core/src/cost_terms.cpp
Implements [this](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/include/moveit/task_constructor/cost_terms.h#L118) TODO.
By passing a vector of joint names to the constructor of `PathLength`, the cost of the path is now computed by only considering these joints. If no vector is passed, all joints are considered.
> Allow to consider specific joints only in PathLength

- core/include/moveit/task_constructor/storage.h
- core/src/stages/generate_grasp_pose.cpp
The `pregrasp` property segfaults when a RobotState.msg is passed to the GenerateGraspPose stage like so:
```cpp
moveit_msgs::RobotState robot_state;
robot_state.is_diff = true;
robot_state.joint_state.name.resize(1);
robot_state.joint_state.name[0] = "panda_finger_joint1";
robot_state.joint_state.position.resize(1);
robot_state.joint_state.position[0] = 0.0;
{
// Sample grasp pose
auto stage = std::make_unique<stages::GenerateGraspPose>("generate grasp pose");
stage->properties().configureInitFrom(Stage::PARENT);
stage->properties().set("marker_ns", "grasp_pose");
stage->setPreGraspPose(robot_state);
...
}
```
This PR may not be the best way to report the bad_any_cast. Also the robot state could fail silently in the `compute` section but is dealt with in the init section. Not sure if a …
> Implement missing pregrasp property for RobotState.msg 

- core/test/CMakeLists.txt
- core/test/stage_mockups.cpp
- core/test/stage_mockups.h
- core/test/test_container.cpp
- core/test/test_cost_terms.cpp
- core/test/test_serial.cpp
- core/test/test_stage.cpp
Makes a lot of sense in general and simplifies independent future tests.
I guess we could unify more of the infrastructure
(TestBase, Standalone<>, append...)
but this is the most important part to have around.
Also fix an unnoticed bug that was triggered during development on the side.
Thanks to @j-kuehn for the initial effort.
> Merge different mockup implementations

- .github/workflows/ci.yaml
To provide accurate coverage information.
It was originally RelWithDebInfo because MoveIt uses it
and Travis's timeout would kick in with the old setup.
According to Robert the timeout should not be a problem anymore with
the GHA ci setup. Actually I don't think the timeout was ever a problem for MTC,
but the config was just copied.
> switch CI ccov job to Debug build

- visualization/motion_planning_tasks/src/task_display.cpp
That's the same fix as https://github.com/ros-planning/moveit/pull/2876.
This fixes #291 in a naive way: 
If the map changes over time, I would actually expect the solution display to use the robot frame transform at the time of planning - not the most recent one as implemented here. However, this timestamp isn't conveyed with our messages yet.
@v4hn @YannickRiou any opinions?
> Update main scene node's pose on updates of robot's model frame

- core/include/moveit/task_constructor/container_p.h
- core/src/container.cpp
I had a hard time reading through this code. I hope, using these tags, it's slightly better now.
> Improve readability of internal-external bimap using tags

- core/include/moveit/task_constructor/container_p.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/storage.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/storage.cpp
- core/test/test_interface_state.cpp
- demo/CMakeLists.txt
- demo/package.xml
- demo/test/CMakeLists.txt
Split out generic improvements from proper Fallbacks support, as per
https://github.com/ros-planning/moveit_task_constructor/pull/287#issuecomment-922040435
> generic improvements

- core/test/CMakeLists.txt
- core/test/stage_mockups.h
- core/test/test_container.cpp
- core/test/test_fallback.cpp
Most of them currently disabled as proposed in
https://github.com/ros-planning/moveit_task_constructor/pull/287#issuecomment-922040435
> new set of fallback tests

- core/test/CMakeLists.txt
Maybe it makes sense to define this in an exported config,
but then why bother until someone needs it.
> define core tests through macros

- demo/test/pick_place.test
In `moveit_resources` 0.8.1 the arg `execution_type` was renamed to `fake_execution_type`.
Thus, unit tests that set the old argument [fail](https://github.com/ros-planning/moveit_task_constructor/actions/runs/1436970425).
To support both, Melodic and Noetic versions of `moveit_resources`, provide both name variants.
Additionally, disable  roslaunch's checking via `pass_all_args="true"`.
An even better approach would be to set the arg `fake_execution_type="last point"` in moveit_resources' test_environment.launch directly - the one or the other way.
> Gracefully handle execution_type

- core/src/solvers/cartesian_path.cpp
- core/src/stages/move_relative.cpp
- demo/src/pick_place_task.cpp
I came across those when debugging a failing `MoveRelative` stage. Essentially we don't need the sanity check for a non-empty trajectory, because we ensure that there is always the start state in there. By the way, we access this first way point a few lines before - without a sanity check:
https://github.com/ros-planning/moveit_task_constructor/blob/5e78622e297b8420195ef83c91ed2784891e7e41/core/src/stages/move_relative.cpp#L300
> Some simple code simplifications

- core/src/stage.cpp
@JafarAbdi, I think you introduced `total_compute_time_`. Did you omit to reset `total_compute_time_` on purpose or was it just missed? I would expect that the total compute time count restarts after a `reset()`.
> Stage::reset() should reset total_compute_time_

- core/src/stages/move_relative.cpp
- core/test/CMakeLists.txt
- core/test/move_relative.test
- core/test/test_move_relative.cpp
`direction` was interpreted relative to the link even when an `ik_frame` was specified.
Solves #318 .
> Fix using IKFrame with MoveRelative

- capabilities/src/execute_task_solution_capability.cpp
Fix the following exception
```
[move_group-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[move_group-1]   what():  goal_handle attempted invalid transition from state EXECUTING with event CANCELED
```
> execute_task_solution_capability: check for canceling request before canceling the goal handle

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/container_p.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/storage.h
- core/include/moveit/task_constructor/task_p.h
- core/include/moveit/task_constructor/utils.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/storage.cpp
- core/src/task.cpp
- core/test/test_container.cpp
- core/test/test_cost_queue.cpp
- core/test/test_fallback.cpp
- core/test/test_interface_state.cpp
- core/test/test_pruning.cpp
- demo/CMakeLists.txt
- demo/src/fallbacks_move_to.cpp
- visualization/motion_planning_tasks/src/local_task_model.cpp
Building on some new (failing) tests introduced by @JafarAbdi and @v4hn, this PR aims to improve (and eventually fix) pruning.
This follows these general ideas:
- If a planning stage fails in a linear pipeline, we can skip all remaining planning stages as well (cols of _left-most_ block)
- However, we need to keep the states in the interfaces as we might re-enable a path later on (left-most cols of _middle_ block)
- A new CONNECT state becomes disabled too (together with its connected branch) (right col of _middle_ block)
- We shouldn‘t prune if there are alternative solutions (_right_ block)
> Fix Pruning

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/container_p.h
- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/storage.h
- core/include/moveit/task_constructor/task_p.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/storage.cpp
- core/src/task.cpp
- core/test/test_container.cpp
- core/test/test_fallback.cpp
- demo/CMakeLists.txt
- demo/src/fallbacks_move_to.cpp
This is a new attempt to correctly implement `Fallbacks`. The key insight is that we need to implement different behavior based on the actual interface type (`GENERATE`, `PROPAGATE_*`, `CONNECT`). These types differ on what they consider a `job` that a child stage should run on till exhaustion before advancing to the next child.
- `GENERATE`: A job is essentially identical to the child itself. The generator child runs until it is exhausted. This is the only operation mode I had in mind when originally implementing the `Fallbacks` stage.
- `PROPAGATE_*`: A job is an external input state. As [pointed out by @v4hn](https://github.com/ros-planning/moveit_task_constructor/pull/280#discussion_r676565782) for each new input state, the Fallbacks container should start over from its first child …
> Fallbacks reworked: Factorize FallbacksPrivate into 3 separate classes

- core/src/stages/fixed_state.cpp
Check collisions for FixedState's scene and report failure if needed.
Optionally, disable the check via the property ignore_collisions=true.
Partially address #337.
> FixedState: ignore_collisions=false

- .github/workflows/ci.yaml
The new galactic branch is needed due to incompatible changes in Rolling-Jammy
> Switch to Galactic CI jobs

- core/include/moveit/task_constructor/merge.h
- core/include/moveit/task_constructor/moveit_compat.h
- core/src/container.cpp
- core/src/merge.cpp
- core/src/solvers/cartesian_path.cpp
- core/src/solvers/joint_interpolation.cpp
- core/src/solvers/planner_interface.cpp
- core/src/stages/connect.cpp
Replaces #333, implementing https://github.com/ros-planning/moveit_task_constructor/pull/333#pullrequestreview-850576619. Fixes #330.
The TimeParameterization method becomes a property in corresponding stages and PlannerInterfaces.
This allows users to configure them easily.
> Make TimeParamerization configurable

- core/include/moveit/task_constructor/storage.h
- core/src/stage.cpp
- core/src/storage.cpp
- core/test/test_pruning.cpp
* Fix #337
If two Connect stages are sequenced, both sides can become ARMED.
However, that means that the wave of PRUNED status updates, shouldn't overwrite a present ARMED state.
* Added a corresponding unit test
* Improved debug output / comments
> Pruning: Relax too strong assertion: PRUNED => !ARMED

- .github/workflows/ci.yaml
- .github/workflows/lsan.suppressions
- core/package.xml
- core/test/move_to.launch.py
- demo/launch/alternative_path_costs.launch.py
- demo/launch/cartesian.launch.py
- demo/launch/demo.launch.py
- demo/launch/ik_clearance_cost.launch.py
- demo/launch/modular.launch.py
- demo/launch/pickplace.launch.py
- demo/package.xml
NOTE: you need https://github.com/ros-planning/moveit2/pull/1274 and https://github.com/PickNikRobotics/rosparam_shortcuts/pull/27 to be able to run the demos
> Use moveit_configs_utils for launch files

- core/src/task.cpp
- core/test/test_move_to.cpp
Fix https://github.com/ros-planning/moveit2_tutorials/pull/426
Backtrace:
```
#1  0x00007ffff7e50972 in moveit::task_constructor::Property::typeName[abi:cxx11]() const () from /home/jafar/workspaces/ros/ws_moveit/devel/lib/libmoveit_task_constructor_core.so
#2  0x00007ffff7e3ca71 in moveit::task_constructor::Introspection::fillTaskDescription(moveit_task_constructor_msgs::TaskDescription_<std::allocator<void> >&)::{lambda(moveit::task_constructor::Stage const&, unsigned int)#1}::operator()(moveit::task_constructor::Stage const&, unsigned int) const [clone .isra.0] ()
from /home/jafar/workspaces/ros/ws_moveit/devel/lib/libmoveit_task_constructor_core.so
#3  0x00007ffff7e17cad in moveit::task_constructor::ContainerBase::traverseRecursively(std::function<bool (moveit::task_constructor::Stage …
```
> Fix task's move constructor

- core/src/solvers/cartesian_path.cpp
This incorporates a newly added MoveIt feature, kinematics cost functions, to pass to `CartesianInterpolator`.
> [ros2]: Add moveit cost function for IK solver as parameter for Cartesian path solver

- core/src/stages/compute_ik.cpp
Instead of just marking an invalid IK solution in red, a comment is added describing the (and only one) collision causing the problem. 
This was done with a lot of help from @v4hn .
> Printing collision info for invalid IK solutions.

- core/include/moveit/task_constructor/solvers/cartesian_path.h
- core/include/moveit/task_constructor/solvers/joint_interpolation.h
- core/include/moveit/task_constructor/solvers/pipeline_planner.h
- core/include/moveit/task_constructor/solvers/planner_interface.h
- core/src/solvers/cartesian_path.cpp
- core/src/solvers/joint_interpolation.cpp
- core/src/solvers/pipeline_planner.cpp
- core/src/stages/move_relative.cpp
- core/src/stages/move_to.cpp
- core/src/utils.cpp
- core/test/test_move_relative.cpp
This fixes #359. There were actually two major issues:
1. #304 broke Cartesian interpolation, wrongly calculating the target frame when rotations were involved (see videos below, were the endeffector should move and rotate about the green axis)
2. MoveIt itself didn't yet support Cartesian interpolation for non-link frames. To fix this, I filed https://github.com/ros-planning/moveit/pull/3197.
old:
https://user-images.githubusercontent.com/5376030/187067390-dd6e7af7-80e9-4b2a-8623-e3b844185e89.mp4
new:
https://user-images.githubusercontent.com/5376030/187067403-528cd575-678a-44ef-8570-5c437a8e4520.mp4
> Fix Cartesian interpolation

- core/include/moveit/task_constructor/cost_terms.h
- core/include/moveit/task_constructor/task.h
- core/python/CMakeLists.txt
- core/python/bindings/src/core.cpp
- core/python/bindings/src/core.h
- core/python/test/test_mtc.py
- core/src/cost_terms.cpp
This implements joint-specific weighting of `PathLength` and `DistanceToReference` (new) costs.
Also expose cost stuff to python.
> CostTerms: joint-weighted costs, expose to python

- core/src/marker_tools.cpp
- rviz_marker_tools/src/marker_creation.cpp
- Link geometries like boxes, spheres, and cylinders might explicitly have a zero size. Don't reset their `scale` to (1,1,1)!
Instead initialize a correct scaling by other means.
- As zero-size markers will be invisible, drop them from the generated marker arrays.
> Fix marker creation: allow zero scale for geometric shapes

- core/include/moveit/task_constructor/solvers/cartesian_path.h
- core/include/moveit/task_constructor/solvers/multi_planner.h
- core/include/moveit/task_constructor/solvers/planner_interface.h
- core/src/CMakeLists.txt
- core/src/solvers/cartesian_path.cpp
- core/src/solvers/joint_interpolation.cpp
- core/src/solvers/multi_planner.cpp
- core/src/solvers/pipeline_planner.cpp
- core/src/solvers/planner_interface.cpp
- demo/src/pick_place_task.cpp
This introduces `MultiPlanner`, a new meta planner implementing the `PlannerInterface`, that runs multiple alternative planners in sequence and returns the first found solution.
This is useful to sequence different planning strategies of increasing complexity, e.g. Cartesian or joint-space interpolation first, then OMPL, ...
This is (slightly) different from the Fallbacks container, as the MultiPlanner directly applies its planners to each individual planning job. In contrast, the Fallbacks container first runs the active child to exhaustion before switching to the next child, which possibly applies a different planning strategy.
As the children planners should be able to use different timeouts (than the stage employing `MultiPlanner`), I also introduced a `timeout` property for all …
> MultiPlanner

- core/include/moveit/task_constructor/container.h
This is a minor change to fix a warning / error when compiling with -Wpedantic.
> remove extra semicolon that triggers compiler warning

- core/include/moveit/task_constructor/task.h
- core/test/test_container.cpp
Considering the (fixed) name of the top-level container is meaningless. The search should start at the wrapped container level.
> Task: findChild() and operator[] should directly operate on stages()

- capabilities/src/execute_task_solution_capability.cpp
- core/src/stages/plugins.cpp
- visualization/motion_planning_tasks/src/plugin_init.cpp
- visualization/motion_planning_tasks/src/pluginlib_factory.h
and include with *.hpp suffix as the old *.h headers have been
forwards for a long time.
Just a tiny cleanup I found on the side.
> use pluginlib consistently

- .github/workflows/ci.yaml
- core/include/moveit/task_constructor/solvers/pipeline_planner.h
- core/src/solvers/pipeline_planner.cpp
- core/test/CMakeLists.txt
- core/test/pick_pa10.cpp
- core/test/pick_pr2.cpp
- core/test/pick_ur5.cpp
- core/test/test_pipeline_planner.cpp
- demo/src/fallbacks_move_to.cpp
This PR refactors the PipelinePlanner to enable the use of MoveIt's parallel planning API. Usage would look for example like this
```cpp
// Configure a set of pipelines to be used
std::unordered_map<std::string, std::string> pipeline_id_planner_id_map;
pipeline_id_planner_id_map["ompl"] = "RRTConnectkConfigDefault";
pipeline_id_planner_id_map["pilz_industrial_motion_planner"] = "LIN";
pipeline_id_planner_id_map["chomp"] = "chomp";
// Construct solver
auto parallel_planner = std::make_shared<mtc::solvers::PipelinePlanner>(node_, pipeline_id_planner_id_map);
// Optional: Configure custom solution selection and/or stopping criterion
parallel_planner->setStoppingCriterionFunction(...);
parallel_planner->setSolutionSelectionFunction(
[](const …
```
> Enable parallel planning with PipelinePlanner

- core/src/stages/current_state.cpp
Port of https://github.com/PickNikRobotics/moveit_task_constructor/pull/7
If no planning scene is received, this stage blocks forever with an inf default
> Set non inf default timeout in current state stage

- core/include/moveit/task_constructor/solvers/cartesian_path.h
- core/include/moveit/task_constructor/solvers/joint_interpolation.h
- core/include/moveit/task_constructor/solvers/pipeline_planner.h
- core/include/moveit/task_constructor/solvers/planner_interface.h
- core/include/moveit/task_constructor/stages/connect.h
- core/include/moveit/task_constructor/storage.h
- core/src/solvers/pipeline_planner.cpp
- core/src/stages/connect.cpp
- core/src/stages/move_relative.cpp
- core/src/stages/move_to.cpp
- core/src/storage.cpp
- core/test/test_pipeline_planner.cpp
- msgs/msg/SolutionInfo.msg
- visualization/motion_planning_tasks/src/task_list_model.cpp
Port of https://github.com/PickNikRobotics/moveit_task_constructor/pull/5
Make planner id part of the trajectory info to add information about the planner that created a trajectory
> Add planner name to trajectory info

- core/src/container.cpp
There should be no harm in running init multiple times
and it actually happens with `Task.init(); ...; Task.plan();`.
However, the logic here overwrites impl with a new type by moving
the old pimpl object a couple of times with operator= through inheritance.
This is eventually caught by StagePrivate::operator=() asserting that the typeid is not identical.
> Fix assert on multi-init() with Fallback

- visualization/motion_planning_tasks/src/task_panel.cpp
- visualization/motion_planning_tasks/src/task_panel.ui
This implementation is far from functional right now and the button confuses users.
@rhaschke I don't know whether you want to keep the whole underlying framework (which is quite sophisticated) around, so I just disabled the UI hook.
I believe you also moved on to specifying tasks in python instead of trying to set them up visually.
> disable hooks for unused rviz-based task construction

- core/src/task.cpp
Implements solution 2 of #353 and should solve it
> Reset joint values in scene diff for execution

- core/include/moveit/task_constructor/stages/generate_random_pose.h
- core/src/stages/CMakeLists.txt
- core/src/stages/generate_pose.cpp
- core/src/stages/generate_random_pose.cpp
> Add random pose generator stage (ros2)

- capabilities/src/execute_task_solution_capability.cpp
- capabilities/src/execute_task_solution_capability.h
Finally address [this comment](https://github.com/ros-planning/moveit_task_constructor/pull/461#issuecomment-1563080267) in #461.
Disclaimer: I am not the original author of these changes. 
This changes the behavior of the execute_task_solution_capability to not accept new execution requests if another request is currently processed. I assume the reason for this is to avoid interruptions because of incorrect execution commands. It is still possible to abort the execution with the CancelCallback.
> Run goalcallback asynchronously

- capabilities/src/execute_task_solution_capability.cpp
- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/trajectory_execution_info.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/storage.cpp
- msgs/CMakeLists.txt
- msgs/msg/SubTrajectory.msg
- msgs/msg/TrajectoryExecutionInfo.msg
This is essentially a ROS2 version of the work in #123, plus some additions based on @henningkayser's review of that PR.
- Add a new `TrajectoryExecutionInfo` ROS message to hold info used when executing the trajectory. Right now it just contains a vector of strings to define controller names used with the trajectory. Add an instance of this message as a field in the `SubTrajectory` message.
- Add a new `TrajectoryExecutionInfo` struct to hold this info as an MTC property.
- Propagate the `"trajectory_execution_info"` property from each stage into the `SubTrajectory` messages output when the task is planned.
- Modify the `ExecuteTaskSolution` capability to copy the controller names into the `RobotTrajectory` prior to execution.
> [ros2] Add Stage property to assign a list of controllers to use when executing the planned trajectory

- core/src/solvers/joint_interpolation.cpp
Hey all,
I noticed an issue where the joint-interpolation planner would successfully plan trajectories that exceeded a joint's limits. This PR adds in the necessary logic to ensure such planning will fail as expected
> [ros2] Check joint bounds when interpolating

- core/src/storage.cpp
- core/src/task.cpp
Address https://github.com/ros-planning/moveit_task_constructor/issues/353#issuecomment-1800860426.
> fixup! Reset joint values in scene diff for execution (#498)

- core/test/test_pipeline_planner.cpp
Fixes failing CI, seen here https://github.com/ros-planning/moveit_task_constructor/pull/509
> Fix test_pipeline_planner parameter

- demo/launch/alternative_path_costs.launch.py
- demo/launch/cartesian.launch.py
- demo/launch/fallbacks_move_to.launch.py
- demo/launch/ik_clearance_cost.launch.py
- demo/launch/modular.launch.py
This PR attempts to get the demos back running for ros2.
However there are still at least two issues left, for which I can't figure out a solution:
1. Running `ros2 launch moveit_task_constructor_demo pickplace.launch.py` crashes with
```
[pick_place_demo-1] [INFO] [1700128364.444205364] [moveit_task_constructor_demo]: Initializing task pipeline
[pick_place_demo-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[pick_place_demo-1]   what():  failed to call rcl_logging_rosout_add_sublogger: The entry of logger 'planning_scene_interface_94074067662208' not exist., at ./src/rcl/logging_rosout.c:438
[pick_place_demo-1] Stack trace (most recent call last):
[pick_place_demo-1] #17   Object "", at 0xffffffffffffffff, in 
[pick_place_demo-1] #16   Object …
```
> fix: demo launch files

- core/src/solvers/joint_interpolation.cpp
:point_up: Small PR to make the errors more informative.
> Distinguish between collision and bound error in JointInterpolationPlanner

- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/stage_p.h
- core/src/container.cpp
- core/src/introspection.cpp
- core/src/stage.cpp
- core/test/CMakeLists.txt
- core/test/stage_mockups.cpp
- core/test/stage_mockups.h
- core/test/test_container.cpp
- core/test/test_mockups.cpp
- core/test/test_pruning.cpp
- core/test/test_serial.cpp
- visualization/motion_planning_tasks/src/remote_task_model.cpp
Attempt to fix https://github.com/ros-planning/moveit_task_constructor/issues/485#issuecomment-1760606116:
https://github.com/ros-planning/moveit_task_constructor/blob/564804bd7bb9e320b304b8c4880d96c6ce63b915/core/src/container.cpp#L491
> [WIP] Debug/Fix #485

- core/include/moveit/task_constructor/stages/connect.h
- core/src/stages/connect.cpp
- core/test/test_move_to.cpp
This fixes #531 but may not fix the actual problem, e.g. it may be the planner that silently fails or something else in the framework.
I just validate the last trajectory waypoint with the goal in the `ConnectStage`. If there is a deviation, the solution is marked as failed and a comment is set. I'm pretty sure you can optimize some of the code ;)
---
On a side note, I had to make sure that the joints where compared correctly (-pi = pi). Currently, when comparing joint position in the [Connect::compatible](https://github.com/ros-planning/moveit_task_constructor/blob/master/core/src/stages/connect.cpp#L124-L125) method, this is not checked. You might reject some valid solutions, e.g the IK solver gives some joint positions in a negative defined angle versus the RobotState who may have a …
> End-state deviates from goal state

- core/include/moveit/task_constructor/stages/generate_grasp_pose.h
- core/src/stages/generate_grasp_pose.cpp
The user can now rotate the object pose about any given axis in the `GenerateGraspPose` stage.
> Expose rotation axis to stage property

- capabilities/src/execute_task_solution_capability.cpp
- core/python/test/rostest_mps.py
- core/src/storage.cpp
Need to generate full planning scene message if planning progressed backwards: The scene_diff field describes PlanningScene changes of the end scene relative to the start scene, while during planning it might be inversed.
Seemingly fixes #405. I would like to add some unit tests before merging.
I also noticed that `ModifyPlanningScene::(add|remove)Object` doesn't yet work in backwards mode. Shall we support this or just issue an error? To reverse, `removeObject()` would require the full `CollisionObject` description (to actually create the object), while currently (for the forward pass) the name suffices.
> Fix Solution::fillMessage()

- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/stage_p.h
- core/src/stage.cpp
Releated to https://github.com/ros-planning/moveit_task_constructor/issues/543. This PR enables the possibility to set independent start and end states when calling the `spawn` method of a Generator stage, while maintaining the previous functionality that uses the same state.
I didn't implement [this overload](https://github.com/ros-planning/moveit_task_constructor/blob/e1b891ba5a346eae14454b3c23f74052d9ada23e/core/include/moveit/task_constructor/stage.h#L369C2-L373C3) as it implies that the trajectory will be empty and it makes no sense to set different start and end states when the robot is not actually moving, right? Or am I missing any specific use case where this could be handy?
I noticed that [`connect`](https://github.com/ros-planning/moveit_task_constructor/blob/e1b891ba5a346eae144 …
> Set independant start and end states in a Generator stage

- core/src/stages/connect.cpp
This is to collect fixups for `ros2` after my force-push.
> Fixups for ROS2

- core/src/stages/connect.cpp
I originally found a small typo in the property comment in https://github.com/moveit/moveit_task_constructor/pull/532, but then decided to also clarify it a little more.
> Fix description of max_distance property of Connect stage

- core/src/introspection.cpp
- core/src/stages/current_state.cpp
- core/src/task.cpp
- visualization/motion_planning_tasks/src/remote_task_model.cpp
- visualization/motion_planning_tasks/src/task_panel.cpp
Directly pass node name and namespace instead of using options.
> Simplify rclcpp::Node creation

- core/src/stages/connect.cpp
- Connect stage: Relax validity check of reached end state
Looks like ROS2 uses a more relaxed goal constraint threshold than ROS1.
For this reason, all end states reached by Connect solutions of pick+place demo
are rejected. This commit relaxes the max_distance threshold of Connect as well.
**MoveIt2 maintainers should check MoveIt2's goal constraint threshold and use a similar value in Connect stage.**
Fixes https://github.com/ros-planning/moveit_task_constructor/issues/540#issuecomment-1988323674
- Revert "Fix generation of Solution msg: consider backward operation"
This reverts commit 4aac679257fb91bed9174096761879d1f14182fc, because MoveIt2 is missing a port of https://github.com/ros-planning/moveit/pull/3538.
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/881
> Temporarily fix issues with execution of pick+place demo

- core/src/stages/move_relative.cpp
When min_distance == max_distance > 0.0, the minimal distance might be missed due to numerical errors.
To avoid this, deactivate minimal distance check and run the full distance as given by max_distance.
Fixes #586. @captain-yoshi, please review.
> MoveRelative: gracefully handle identical min/max distance

- core/src/stages/move_relative.cpp
We have run into an issue a few times with `MoveRelative` relative that causes a crash. If the ``PlannerInterface` implementation returns a trajectory with no waypoints, but a non-null `robot_trajectory`, then the back of an empty vector is accessed via `robot_trajectory->getLastWayPointPtr()` leading to a crash. 
A potential fix is to consider empty trajectories as a failed plan. We run into this issue frequently when the robot starts in or very close to a collision.
> Fix `MoveRelative` potentially empty trajectory issue

- core/include/moveit/task_constructor/stage_p.h
- core/include/moveit/task_constructor/task.h
- core/src/stage.cpp
- core/src/task.cpp
- core/test/stage_mockups.h
- core/test/test_container.cpp
This is a follow up to #597. To reduce time when preempting a task for each stages.
Stages now checks if there has been a preempt request before doing the `compute()` method. Let me know if there would be a cleaner way to achieve this.
This does not preempt a stage that has already began the compute() method.
> Reduce preempt stop time in stages

- rviz_marker_tools/CMakeLists.txt
- rviz_marker_tools/include/rviz_marker_tools/marker_creation.h
- rviz_marker_tools/package.xml
`liburdfdom-dev` is not actually used. Only `liburdfdom-headers-dev`.
I cleaned up a few other things along the way while working on building packages for it in [my ros-o github builder](https://v4hn.github.io/ros-o-builder/).
> clean up dependencies for rviz_marker_tools

- core/include/moveit/python/task_constructor/properties.h
- core/include/moveit/task_constructor/solvers/cartesian_path.h
- core/python/bindings/src/solvers.cpp
- core/src/solvers/cartesian_path.cpp
- demo/src/fallbacks_move_to.cpp
This should be merged only after the next MoveIt release.
> Update API: JumpThreshold -> CartesianPrecision

- core/include/moveit/task_constructor/fmt_p.h
- core/python/bindings/src/solvers.cpp
- core/src/container.cpp
- core/src/cost_terms.cpp
- core/src/properties.cpp
- core/src/stage.cpp
- core/src/stages/compute_ik.cpp
- core/src/stages/connect.cpp
- core/src/stages/fix_collision_objects.cpp
- core/src/stages/modify_planning_scene.cpp
for special eigen formatter, which is not available in fmt9+ (found on Debian testing).
https://github.com/fmtlib/fmt/issues/3465
https://stackoverflow.com/a/73755864/21260084
@rhaschke Not sure whether you are ok with the generic wrapper header as you usually argue for minimal includes. The concrete issue currently only affects a single location where an Eigen datatype is formatted. But I believe as we use libfmt all over the place (as you introduced at some point), I would also expect to be able to format Eigen datastructures everywhere without additional includes & helpers.
> Wrapper FMT header for compatibility

- .github/workflows/ci.yaml
- core/cmake/pybind11.cmake.in
- core/python/CMakeLists.txt
- core/python/bindings/src/core.cpp
On Jammy, pybind11 complains with:
```
CMake Warning at python/pybind11/tools/pybind11Tools.cmake:24 (message):
Set PYBIND11_PYTHON_VERSION to search for a specific version, not
PYTHON_VERSION (which is an output).  Assuming that is what you meant to do
and continuing anyway.
```
Looks like `PYTHON_VERSION_STRING` is not defined anymore.
> Silent pybind11 warning

- core/include/moveit/task_constructor/container.h
- core/include/moveit/task_constructor/stage.h
- core/include/moveit/task_constructor/task.h
- core/src/container.cpp
- core/src/stage.cpp
- core/src/stages/compute_ik.cpp
- core/src/stages/current_state.cpp
- core/src/stages/fixed_cartesian_poses.cpp
- core/src/stages/generate_pose.cpp
- core/src/stages/generate_random_pose.cpp
- core/src/task.cpp
Don't use command-line warnings, but spawn failure solutions. This fixes https://github.com/moveit/moveit_task_constructor/issues/650#issuecomment-2629030464:
```
Failing stage(s):
compute ik (0/4): ik frame unknown in robot: 'foo'
```
Additionally, to correctly report ComputeIK's failure comments, I had to adapt `explainFailure()`.
> ComputeIK: report failures the modern way

- capabilities/src/execute_task_solution_capability.cpp
Alternative implementation to #652
> Provide feedback during ExecuteTaskSolution action

- core/src/stages/move_relative.cpp
- core/test/test_move_relative.cpp
Fixes #664. Do not enforce position bounds, let the stage fail if joints are outside the limits instead of clamping to valid positions.
There are maybe some who would actually want to move relative up to the position limit. But there's a lot chances that this will fail in subsequent stages.
> Remove clamping of joint constraint in MoveRelative stage

- capabilities/test/test_task_execution.cpp
- core/src/task.cpp
Integrating preempt execution into my downstream application I found that when reusing my Task object between requests it would fail planning after preempting motion because the `preempt_requested_` flag was never reset. Sorry for missing this in #684 I thought the flag was reset on each `plan()` request but it looks like #597 has some use case where that causes issues.
> Reset preempt_request after canceling execution

- .github/workflows/format.yaml
- .pre-commit-config.yaml
- core/CMakeLists.txt
- core/python/CMakeLists.txt
- core/python/bindings/CMakeLists.txt
- core/python/bindings/src/properties.cpp
Using this method in custom bindings results in an undefined symbol error for `PropertyConverterBase::insert`, which is defined in the `pymoveit_mtc` extension. 
To allow linking all relevant classes and functions, I factored out these components into a new shared library `libmoveit_task_constructor_core_python_tools.so`, which is exported by the catkin package.
> Enable use of properties::_class::property for custom python bindings

- capabilities/src/execute_task_solution_capability.cpp
This PR resolves the build errors by adding the missing `#include <fmt/ranges.h>` where `fmt::join` is used.
> fmt/ranges.h added in execute_task_solution_capability.cpp

- core/src/storage.cpp
- core/test/CMakeLists.txt
- core/test/test_storage.cpp
Fixes #638.
I'm not sure if this has other implications.
----
**EDIT**
> That's a cheap (in terms of lines of code) solution indeed. 👍 It is quite costly with meshes in the scene
Actually that is currently my problem as I have multiple meshes. While it adds only 17ms, this will be passed to the controller which will add more CPU time. And finally, I recompute the PlanningScene object from the msg, in a queue, to be able to set the planning scene (FixedState stage) for subsequent  MTC Tasks. Without this fix I loose 3 seconds from applying the scene msg diff that is already up to date.
> [wip] Fix duplicate scenes in Solution.msg in forward planning
