moveit/moveit_task_constructor

CMakeLists.txt, include/moveit_task_constructor/debug.h, include/moveit_task_constructor/storage.h, include/moveit_task_constructor/task.h, src/debug.cpp, src/demo/plan_pick_trixi.cpp, src/demo/plan_pick_ur5.cpp, src/subtask.cpp, src/task.cpp
publish one plan at a time
wait for a keypress in between
remove "handled" flag from SubTrajectory: I don't see it's use... Don't you want to iterate over all possible plans?
=> cleanup publish plans

include/moveit_task_constructor/debug.h, src/debug.cpp
It doesn't make sense to use a reference to a pointer.
=> fix for-loop argument types

LICENSE.txt, core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/introspection.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stage_p.h, core/include/moveit/task_constructor/stages/cartesian_position_motion.h, core/include/moveit/task_constructor/stages/current_state.h, core/include/moveit/task_constructor/stages/generate_grasp_pose.h, core/include/moveit/task_constructor/stages/gripper.h, core/include/moveit/task_constructor/stages/move.h, core/include/moveit/task_constructor/storage.h, core/include/moveit/task_constructor/task.h, core/include/moveit/task_constructor/utils.h, core/src/container.cpp, core/src/introspection.cpp, core/src/stage.cpp, core/src/stages/cartesian_position_motion.cpp, core/src/stages/current_state.cpp, core/src/stages/generate_grasp_pose.cpp, core/src/stages/gripper.cpp, core/src/stages/move.cpp, core/src/storage.cpp, core/src/task.cpp, visualization/motion_planning_tasks/src/pluginlib_factory.h, visualization/visualization_tools/include/moveit/visualization_tools/display_solution.h, visualization/visualization_tools/src/display_solution.cpp
@rhaschke Please confirm and merge.
=> add full license information

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stages/generate_grasp_pose.h, core/src/container.cpp, core/src/stages/generate_grasp_pose.cpp, core/test/test_container.cpp, visualization/motion_planning_tasks/src/task_panel.cpp
* small fixes
* unittests + fixes for ParallelContainers
=> rhaschke's master

core/demo/plan_pick_pa10.cpp, core/demo/plan_pick_trixi.cpp, core/demo/plan_pick_ur5.cpp, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/stages/modify_planning_scene.h, core/include/moveit/task_constructor/stages/pick.h, core/include/moveit/task_constructor/stages/simple_grasp.h, core/src/container.cpp, core/src/stages/CMakeLists.txt, core/src/stages/generate_grasp_pose.cpp, core/src/stages/pick.cpp, core/src/stages/simple_grasp.cpp, core/test/test_container.cpp
Pick stage is working now, but still w/o scheduling. This goes on top of rhaschke-master!
=> Pick stage

core/src/stages/fix_collision_objects.cpp, core/src/stages/move_to.cpp
reverted `(void) variable;`
minor formatting ;-)
=> minor formatting changes

core/include/moveit/task_constructor/task.h, core/src/stage.cpp, core/src/stages/compute_ik.cpp, core/src/stages/connect.cpp, core/src/task.cpp
These are pretty much the useful&required modifications I apply locally.
=> remaining local modifications

core/include/moveit/task_constructor/solvers/pipeline_planner.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stages/compute_ik.h, core/include/moveit/task_constructor/storage.h, core/src/solvers/pipeline_planner.cpp, core/src/stage.cpp, core/src/stages/compute_ik.cpp
A set of (from my perspective) uncontroversial commits to improve current master.
Feel free to cherry-pick commits to master.
=> various minor improvements

rviz_marker_tools/src/marker_creation.cpp, visualization/motion_planning_tasks/src/CMakeLists.txt, visualization/motion_planning_tasks/src/global_settings.ui, visualization/motion_planning_tasks/src/task_panel.cpp, visualization/motion_planning_tasks/src/task_panel.h, visualization/motion_planning_tasks/src/task_panel.ui, visualization/motion_planning_tasks/src/task_panel_p.h
This branch addresses several visualization issues. It relies on https://github.com/ros-visualization/rviz/pull/1303, which is not yet merged, nor released. To use this branch you should build rviz from source, e.g. using https://github.com/rhaschke/rviz/commits/melodic-devel.
**This PR branch is included in #81. Please, fast-forward to #81 for merging.**
=> visualization improvements

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/stage_p.h, core/src/container.cpp, core/src/stage.cpp, core/src/task.cpp, core/test/test_container.cpp
@v4hn, you offline reported about issues with interface deduction. Indeed, I could reproduce some issues when using nested SerialContainers. This PR should solve these issues.
**This PR branch is included in #81. Please, fast-forward to #81 for merging.**
=> fix interface deduction

README.md
Currently the README scares would be contributors away. We'd really like to start using this for our various projects, and integrating it more tightly into the main moveit project. Of course all software is always under development and getting better, but considering you published a great paper on this, I'd say its as usable as ever.
=> Clarify that the MTC is usable

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/cost_queue.h, core/include/moveit/task_constructor/properties.h, core/include/moveit/task_constructor/solvers/cartesian_path.h, core/include/moveit/task_constructor/solvers/pipeline_planner.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stages/compute_ik.h, core/include/moveit/task_constructor/stages/connect.h, core/include/moveit/task_constructor/stages/fixed_cartesian_poses.h, core/include/moveit/task_constructor/stages/generate_grasp_pose.h, core/include/moveit/task_constructor/stages/generate_place_pose.h, core/include/moveit/task_constructor/stages/generate_pose.h, core/include/moveit/task_constructor/stages/move_relative.h, core/include/moveit/task_constructor/stages/move_to.h, core/include/moveit/task_constructor/stages/pick.h, core/include/moveit/task_constructor/stages/simple_grasp.h, core/include/moveit/task_constructor/storage.h, core/include/moveit/task_constructor/task.h, core/src/container.cpp, core/src/stage.cpp, core/src/stages/CMakeLists.txt, core/src/stages/compute_ik.cpp, core/src/stages/fixed_cartesian_poses.cpp, core/src/stages/generate_place_pose.cpp, core/src/stages/simple_grasp.cpp, core/src/task.cpp, core/test/test_container.cpp, core/test/test_stage.cpp, visualization/motion_planning_tasks/properties/property_from_yaml.cpp
This PR is a collection of various improvements (on the master branch) as well as of commits to fix the broken Travis (on branch fix-interface-deduction).
Would be great, if you @v4hn or @henningkayser could have a quick look.
As usual, this branch is intended for fast-forward-merging, which is only possible from cmdline.
=> fast forward master

core/include/moveit/task_constructor/stages/move_to.h, core/src/stages/move_to.cpp
A minor patch my students came up with.
=> Overload setGoal to accept joint value map as argument

visualization/motion_planning_tasks/src/task_panel.cpp
=> add missing header

core/src/stages/move_relative.cpp, core/src/stages/move_to.cpp
Fix for https://github.com/ros-planning/moveit_task_constructor/commit/52fdf30433028c1f41d7feb2bd2f593d4ef4d305#r35592047
=> MoveTo/MoveRelative: report failure on invalid trajectories

core/CMakeLists.txt, core/src/stages/fix_collision_objects.cpp, core/src/stages/move_relative.cpp, demo/src/cartesian.cpp, demo/src/modular.cpp
This set of commits comprises several minor improvements to the demos, fixing recently raised issues (#113, #114).
Most importantly, the last commit should provide compatibility to the MoveIt master branch.
If you are fine with these commits, @v4hn, please fast-forward master.
=> Forward master

.travis.yml
Code coverage reporting has been merged into moveit_ci.  This is ready for review.  @henningkayser
=> code coverage reporting

core/include/moveit/task_constructor/task.h, core/src/task.cpp
Add a return value to check if the execution was successful.
=> Add return value to Task::execute

demo/config/panda_config.yaml, demo/src/pick_place_task.cpp
The parameter describes the maximum number of found solutions before further planning is aborted.
As this is the demo package, it should be correct.
@henningkayser Please review and merge. I ask you so you can fixup your own setups if they rely on this demo.
=> planning_attempts -> max_solutions

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stage_p.h, core/include/moveit/task_constructor/task.h, core/src/container.cpp, core/src/introspection.cpp, core/src/stage.cpp, core/src/task.cpp, visualization/motion_planning_tasks/src/task_display.h, visualization/motion_planning_tasks/src/task_panel.cpp
A small set of patches, adjusting interfaces as discussed before and cleaning up a few warnings clang comments on.
=> adjust interfaces & address minor warnings

core/include/moveit/task_constructor/merge.h, core/src/container.cpp, core/src/merge.cpp, core/src/solvers/joint_interpolation.cpp, core/src/stages/connect.cpp, demo/src/cartesian.cpp, visualization/CMakeLists.txt, visualization/motion_planning_tasks/src/CMakeLists.txt, visualization/motion_planning_tasks/utils/CMakeLists.txt
Hi @v4hn, I have a set of fixes lying around as well.
=> Some fixes

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stage_p.h, core/src/container.cpp, core/src/stage.cpp, core/src/task.cpp, core/test/test_container.cpp, demo/scripts/grasp.py, demo/scripts/pick.py, notes.org, pick+place.org, test.py, visualization/motion_planning_tasks/src/task_list_model.cpp
@rhaschke Here's the big patch I talked about yesterday.
I added/adjusted quite a few tests, with minor improvements on the side.
Sorry it all got mashed up in one huge commit but I wanted to omit functionally broken commits and most of this patch is interrelated.
a few minor changes are left as standalone commits before the main one.
=> rework interface pruning

visualization/motion_planning_tasks/src/task_list_model.cpp
... to trigger visualization updates.
That was a rather obvious mistake on my side, sorry :(
Fixes #184
=> Fixup: forward dataChanged to QTreeView

core/include/moveit/task_constructor/cost_queue.h, core/include/moveit/task_constructor/properties.h, core/include/moveit/task_constructor/stage_p.h, core/include/moveit/task_constructor/storage.h, core/include/moveit/task_constructor/task.h, core/include/moveit/task_constructor/utils.h, core/src/container.cpp, core/src/introspection.cpp, core/src/properties.cpp, core/src/stages/compute_ik.cpp, core/src/stages/fixed_cartesian_poses.cpp, core/src/task.cpp, core/test/test_cost_queue.cpp, core/test/test_interface_state.cpp, visualization/motion_planning_tasks/src/local_task_model.cpp, visualization/motion_planning_tasks/src/remote_task_model.cpp, visualization/motion_planning_tasks/src/task_display.cpp, visualization/motion_planning_tasks/src/task_list_model.h, visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp, visualization/motion_planning_tasks/utils/icon.cpp, visualization/motion_planning_tasks/utils/tree_merge_proxy_model.cpp
A set of minor patches improving the general state.
I will just merge these once CI succeeds.
=> minor patches 2.0

core/include/moveit/task_constructor/solvers/joint_interpolation.h, core/include/moveit/task_constructor/stage.h, core/src/introspection.cpp, core/src/stage.cpp, core/src/task.cpp, msgs/msg/StageStatistics.msg, visualization/motion_planning_tasks/src/remote_task_model.cpp, visualization/motion_planning_tasks/src/task_list_model.cpp
most of them are cosmetic, f07f16d is the biggest actual change, adding an interface to access the stage id.
@felixvd
=> Another batch of minor patches

codecov.yaml, core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/src/container.cpp, visualization/motion_planning_tasks/src/remote_task_model.cpp
This PR includes some simple improvements and fixes, mainly in the `Merger` stage (separate branch).
Please "merge" via fast-forward.
=> Several minor fixes

core/src/stages/connect.cpp, core/src/task.cpp, core/test/test_container.cpp, visualization/motion_planning_tasks/properties/property_from_yaml.cpp, visualization/motion_planning_tasks/src/task_display.cpp, visualization/motion_planning_tasks/src/task_display.h, visualization/motion_planning_tasks/src/task_panel.cpp
I came across several larger and smaller issues, which I addressed in these individual commits. See their commit messages for details.
**This PR is best merged via #216.**
=> Fix various issues

core/src/introspection.cpp
Fix: https://github.com/ros-planning/moveit_task_constructor/issues/222
=> introspection: Fix hostname having  as character

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/container_p.h, core/include/moveit/task_constructor/stage_p.h, core/include/moveit/task_constructor/storage.h, core/src/container.cpp, core/src/stage.cpp, core/test/test_serial.cpp
Followup to #250 and should fix #247 (up to the additional pruning you mentioned in the last post @rhaschke).
=> prune outside states on failure inside container

core/test/pick_ur5.cpp, core/test/test_cost_terms.cpp
small set of patches as multiple times before.
=> Minor patches

core/CMakeLists.txt, core/motion_planning_stages_plugin_description.xml, core/src/stages/CMakeLists.txt, core/src/stages/current_state.cpp, core/src/stages/plugins.cpp
=> Fix some memory issues pointed out by sanitizer

capabilities/CMakeLists.txt, capabilities/package.xml, capabilities/src/execute_task_solution_capability.cpp, core/CMakeLists.txt, core/include/moveit/task_constructor/moveit_compat.h, core/src/cost_terms.cpp, core/src/solvers/cartesian_path.cpp, core/src/stage.cpp, core/src/stages/compute_ik.cpp, core/src/stages/fix_collision_objects.cpp, core/src/stages/generate_place_pose.cpp
=> Fix some issues with ComputeIK

core/include/moveit/task_constructor/moveit_compat.h, core/include/moveit/task_constructor/stage.h, core/include/moveit/task_constructor/stages/fixed_state.h, core/include/moveit/task_constructor/stages/move_to.h, core/include/moveit/task_constructor/utils.h, core/src/CMakeLists.txt, core/src/solvers/joint_interpolation.cpp, core/src/stages/compute_ik.cpp, core/src/stages/fixed_state.cpp, core/src/stages/move_relative.cpp, core/src/stages/move_to.cpp, core/src/utils.cpp, core/test/CMakeLists.txt, core/test/models.cpp, core/test/move_to.test, core/test/test_move_to.cpp, visualization/motion_planning_tasks/src/pluginlib_factory.h
- implement a simple IK interface for `JointInterpolationSolver` Cartesian goals
- fix some bugs
- include attached objects/subframe fixes similar to #296
=> Add MoveTo tests & make them pass

core/src/stages/compute_ik.cpp, core/src/stages/generate_place_pose.cpp
These are some commits I had lying around...
- Better markers for ComputeIK
- Allow to _configure_ `z-flip` in `GeneratePlacePose`, i.e. placing object upside-down
=> Some small improvements

core/package.xml
Signed-off-by: Tyler Weaver <tyler@picknik.ai>
I needed this change to get a source build on rolling working.
=> Add test depend for source build

core/src/solvers/cartesian_path.cpp, core/src/task.cpp, core/test/test_move_to.cpp
=> Merge ROS1 changes

visualization/motion_planning_tasks/src/task_panel.cpp
=> Maintain compatibility to Qt 5.12 (for Focal)

core/include/moveit/task_constructor/container.h, core/include/moveit/task_constructor/task.h, core/python/bindings/src/core.cpp, core/python/test/test_mtc.py, core/src/container.cpp
=> Expose ContainerBase::childByIndex via operator[](int)

rviz_marker_tools/package.xml
=> Add missing dependency

.gitmodules
As mentioned [here](https://github.com/ros-planning/moveit_task_constructor/pull/423#issuecomment-1418878818).
=> revert to upstream pybind repository

capabilities/src/execute_task_solution_capability.cpp, capabilities/src/execute_task_solution_capability.h, core/src/solvers/pipeline_planner.cpp
Required to align with changes introduced by [8bfe782d6254997d185644fa3eb358d2b79d69b2](https://github.com/ros-planning/moveit2/commit/8bfe782d6254997d185644fa3eb358d2b79d69b2).
=> remove underscore from public members in MotionPlanResponse

core/src/stages/compute_ik.cpp
I was wondering, why ComputeIK reported collisions of static scene objects, while MoveIt happily ignores those.
The reason was that ComputeIK was doing collision checking for the full, unrestricted scene.
Now, it's limited to the JMG as well.
Maybe, MoveIt needs to be fixed to include downstream links of the JMG as well: If the JMG moves, those links will move as well... That could be the reason for end-effector collisions reported by users from time to time. However, this needs further inspection. I didn't have time for this (yet).
=> ComputeIK: Limit collision checking to JMG

core/src/introspection.cpp
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/458#issuecomment-1173044746
=> introspection: remove any invalid ROS-name chars from hostname

core/src/stages/move_relative.cpp
Fixes #468. Addressing Noetic.
=> Gracefully handle NULL robot_trajectory

.github/workflows/ci.yaml, core/include/moveit/task_constructor/stages/modify_planning_scene.h, core/include/moveit/task_constructor/storage.h, core/python/bindings/src/core.cpp, core/python/bindings/src/stages.cpp, core/python/test/rostest_mps.py, core/python/test/rostest_mtc.py, core/python/test/rostest_mtc.test, core/src/introspection.cpp, core/src/stages/modify_planning_scene.cpp, core/src/storage.cpp, core/src/task.cpp, demo/src/pick_place_task.cpp
Failing unit test to reproduce #457 and fixing it.
=> More tests for ModifyPlanningScene

core/test/test_pipeline_planner.cpp
Addresses breaking changes introduced by https://github.com/ros-planning/moveit2/pull/2457
=> Update unittests to breaking moveit2 update

core/python/bindings/src/core.cpp, core/python/bindings/src/solvers.cpp, core/python/bindings/src/utils.h, demo/scripts/multi_planner.py
Exposes MultiPlanner (#429) to Python APIs.
=> Expose MultiPlanner to Python

core/test/test_fallback.cpp
https://github.com/moveit/moveit_task_constructor/issues/581#issuecomment-2147985474
=> Add unittest for #581
